### PR TITLE
Add a link to the live demo and some minor polishing of the demo and README

### PR DESCRIPTION
**Pull request by CristianCantoro**
Hi,

here's another pull request (the last, I think :wink:). I've added a link to [rawgit.com](https://rawgit.com) that allows rendering the demo page live (and it's updated in a short time if a new commit is pushed).

I have also added a new section in the README. I'm very happy with the results.

C

### CODE REVIEW

**Comment by oofaish** [comment]
Nice - would be nice though if some of the example had colour'ed cubes? rather than all white? looks rather sad 🤣

**Comment by oofaish** [comment]
(I am happy to merge, but if you agree then feel free to change - otherwise will merge later)

**Comment by CristianCantoro** [comment]
Ok, I will change some colors! (or, rather, colo*u*rs :P)

**Comment by CristianCantoro** [comment]
Actually. I did some more improvements:
* I've changed the colors in the demo
* I've added more than a little bit of javascript to the demo so that:
  - it will continue to work in the future (counters are initialized relative to the current time)
  - I've added buttons to reload counters to show how `onEnd` callbacks and `triggerEnd` work
(the logic is that for simple examples there is the README)
* the event triggered at the end of the counter now contains the original options
* I have changed the behavior of the counter when 60 seconds are left (it displays `60 seconds` instead of `1 minute 0 seconds` because sometimes this was displayed as `0 minutes 0 seconds`)

C

**Pull request merged**
